# Generated by Django 3.0.3 on 2020-02-24 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20200224_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='unlike_user_set',
            field=models.ManyToManyField(blank=True, related_name='unlike_user_set', through='posts.Unlike', to=settings.AUTH_USER_MODEL),
        ),
    ]
